version: 2
updates:
  # Monitor Ruby dependencies
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "dependabot[bot]"
    assignees:
      - "dependabot[bot]"
    commit-message:
      prefix: "📦"
      include: "scope"

  # Monitor Node.js dependencies (if any)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "dependabot[bot]"
    assignees:
      - "dependabot[bot]"
    commit-message:
      prefix: "📦"
      include: "scope"

  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "dependabot[bot]"
    assignees:
      - "dependabot[bot]"
    commit-message:
      prefix: "🔧"
      include: "scope"