name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.3', '3.4']

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Bower
      run: npm install -g bower

    - name: Install frontend dependencies
      run: |
        if [ -f "bower.json" ]; then
          bower install --allow-root
        fi

    - name: Check Middleman version
      run: bundle exec middleman version

    - name: Validate configuration
      run: bundle exec middleman config

    - name: Build site (test)
      run: bundle exec middleman build

    - name: Check build output
      run: |
        echo "Build output size:"
        du -sh build/
        echo "Files in build:"
        ls -la build/